Cargo.toml

Only need one review but tagging two, whoever is first wins. This pins base64 to 0.22.1 for mongosql.
So...
I've finally determined the cause of release failure compared to snapshot and patch successes. The main thing we do differently in evergreen on release is use `cargo-edit` to set the package versions. This causes the lockfile to change, resulting in, for reasons unknown, base64 in `mongosql` to downgrade to 0.13.1 from 0.22.1. 
I was able to reproduce the error we're seeing in release locally, exactly as we're seeing it on evergreen. I pinned the version and it cleared the error up even after setting the version to something like 1.6.1

pin-base64

---

go/go.mod
go/mongosql/exclude_namespaces_test.go
go/mongosql/mongosql_test.go

I didn't even consider this initially, my bad. I forgot about how unforgiving go paths are. I'll re-release the same tags once this is fixed.

ensure go paths are updated properly

---

agg-ast/schema_derivation/src/schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation_tests/untagged_ops.rs
mongosql/src/schema/definitions.rs
mongosql/src/schema/test.rs

Migrated from the old private repo.
This PR updates schema derivation for addition, subtraction, and multiplication. It is still technically incomplete but I think at this point I'll file a follow-up ticket for remaining work.
My main goals were:
1. Fix multiplication to properly account for nullability. It previously did not acknowledge when it was possibly nullable and now it does.
2. Fix addition and subtraction with respect to Date arguments. The first implementation I merged under this ticket number too strictly assumed the result type would be Date in certain circumstances. Now, it returns the full set of possible types when an operand MAY or MUST be Date.
The things left to do are more precise numeric handling for Addition and Multiplication. Specifically, if you have `AnyOf(Int, …

SQL-2357: Refine schema derivation for Addition, Subtraction, and Multiplication

---

mongosql/src/algebrizer/test.rs
mongosql/src/internal_spec_test/mod.rs
mongosql/src/mir/schema/test/expressions/aggregate.rs
mongosql/src/mir/schema/test/usererror.rs
mongosql/src/schema/definitions.rs
mongosql/src/schema/test.rs
tests/errors/schema.yml
tests/spec_tests/query_tests/group_by.yml
tests/spec_tests/type_constraint_tests/operators.yml
tests/spec_tests/type_constraint_tests/scalar_functions.yml

This PR implements `Array` and `Document` self-comparison by updating the `is_comparable_with` method as described in the design doc. I had to make a few more changes than what we initially documented since I wanted to make `Document` and `Array` comparison match all other types (i.e. comparison to `null`/`missing`/`unsat`/`any` works the same for them as for everything else). Unit tests are updated to reflect these new semantics.
For now, I decided to _skip_ now-failing spec tests because we have dedicated tickets in the epic to audit them and decide if they should be updated or removed. Let me know if you prefer I do any of those updates as part of this PR. I think deferring to the follow-up spec test tickets is totally fine. I want to schedule and pick those up next anyway so those …

SQL-2618: Enable Document and Array self-comparison

---

Cargo.lock
mongosql/src/internal_spec_test/mod.rs
tests/spec_tests/query_tests/group_by.yml
tests/spec_tests/type_constraint_tests/group_by.yml

This PR updates the `group_by.yml` spec query and type constraint tests. For the query tests, I removed the accumulator type-checking tests in favor of the more robust type constraint test suite; I updated the group key test to use an `AnyOf` schema instead of `Document` (since `Document` is now valid). For the type constraint tests, I added tests for distinct versions of all accumulators, including those that already had non-distinct tests. This covers everything described in the design doc for this ticket.
Note that `COUNT(DISTINCT *)` and `COUNT(DISTINCT col1, col2, ...)` will be spec tested as part of their respective implementation tickets.

SQL-2623: Update spec testing for GROUP BY accumulators to demonstrate document and array self-comparability

---

tests/spec_tests/query_tests/operators_comparison.yml
tests/spec_tests/type_constraint_tests/operators.yml

This PR `operators_comparison.yml` spec query tests and the `operators.yml` spec type constraint tests. For the query tests, I added binary comparison operator correctness tests for arrays and for documents using the data included in the design doc. I got the expected values by running the queries manually against mongodb. For the type constraint tests, I updated the `comparisonValidTypes` anchor to include `array` and `document` self-comparison entries (I also included `undefined` since that was previously missing). Future tickets will cover the remaining impacted expressions (`BETWEEN`, `NULLIF`, `CASE`, subquery comparisons).

SQL-2624: Add/Update spec tests for binary comparison operators

---

Cargo.lock
agg-ast/schema_derivation/Cargo.toml
agg-ast/schema_derivation/src/lib.rs
agg-ast/schema_derivation/src/schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation_tests/expression.rs
agg-ast/schema_derivation/src/schema_derivation_tests/mod.rs
agg-ast/schema_derivation/src/schema_derivation_tests/stage.rs
agg-ast/schema_derivation/src/schema_derivation_tests/tagged_ops.rs
agg-ast/schema_derivation/src/schema_derivation_tests/untagged_ops.rs
mongosql/src/schema/definitions.rs

This pr is much shorter than it looks -- I split the macro for testing derive_schema into two so that it can easily deserialize stages and expressions (could perhaps make it one, if we wanted to get fancy, but it was easier this way).
Two stages of the original seven in this ticket were skipped: $redact (that will be hard and annoying -- certainly worth its own ticket) and $geoNear (it was not going to be possible to construct a meaningfully accurate result_set_schema because the information needed to get the type of the coordinates being used would be imbedded in the index, not in the schema).

SQL-2370: implement schema derivation for misc stages

---

errors.md
mongosql/src/air/desugarer/accumulators.rs
mongosql/src/air/desugarer/testdata/desugar_accumulators.yml
mongosql/src/algebrizer/test.rs
mongosql/src/mir/schema/errors.rs
mongosql/src/mir/schema/mod.rs
mongosql/src/translator/stages.rs
mongosql/src/translator/test/stages.rs
mongosql/src/util/mod.rs
tests/errors/schema.yml
tests/spec_tests/query_tests/group_by.yml

This PR implements support for `COUNT(DISTINCT *)`. It also updates the implementation of `COUNT(*)`, `COUNT(<expr>)`, and `COUNT(DISTINCT <expr>)` to be consistent in terms of implementation and behavior.
There's a lot going on in this one:
- I refactored the `desugarer/accumulators.rs` file to better support this accumulator, and I set it up for SQL-2622 (support multi-column `COUNT` aggregations).
- As noted in the ticket, I removed the `CountDistinctStarNotSupported` error from the `mir/schema` errors library, and updated the translation pipeline to support this expression.
- I added spec tests for `COUNT(*)` and `COUNT(DISTINCT *)`. We don't have an explicit `COUNT(DISTINCT <expr>)` test in the spec query tests, but we do have a test that implicitly covers this. **Do you think I …

SQL-2621: Implement COUNT(DISTINCT *)

---

mongosql/src/mir/optimizer/stage_movement/mod.rs
mongosql/src/mir/optimizer/stage_movement/test.rs

This PR allows limit to move the same as offset. It also refactors in a few ways:
* Both limit and offset are referred to as "pagination" and methods are updated accordingly.
* Offset and Limit and now pagination invalidating. This is to prevent moving a limit ahead of an offset.
* I attempted to make the comments a bit more clear and pronounced.
* Tests that had a Limit stage have had that stage removed, and a few tests have been added to show that Limit now moves. This is an attempt to show the behavior in more isolation.

SQL-2646: Implement Limit Movement

---

mongosql/src/air/definitions.rs
mongosql/src/algebrizer/definitions.rs
mongosql/src/algebrizer/test.rs
mongosql/src/codegen/match_query.rs
mongosql/src/codegen/test/match_query.rs
mongosql/src/mir/definitions.rs
mongosql/src/mir/optimizer/rewrite_to_match_language/mod.rs
mongosql/src/mir/optimizer/rewrite_to_match_language/test.rs
mongosql/src/mir/optimizer/stage_movement/mod.rs
mongosql/src/mir/schema/mod.rs
mongosql/src/translator/match_query.rs
mongosql/src/translator/test/stages.rs

This PR ended up doing two things:
* Change {$match: {$expr: false}} to {$match: {_id: MinKey, $expr: false}}
* Change Join algebrization to always use a separate Filter instead of the Condition
* This is fine because Stage Movement will still move them into the condition, if it makes sense, but will move it above the join now when it can! (if the condition constant)

SQL-2651: Optimize WHERE/ON false queries such that they will always use index scans

---

agg-ast/ast/src/definitions.rs
agg-ast/ast/src/serde_test.rs
agg-ast/schema_derivation/src/lib.rs
agg-ast/schema_derivation/src/schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation_tests/mod.rs
agg-ast/schema_derivation/src/schema_derivation_tests/stage.rs
agg-ast/schema_derivation/src/schema_derivation_tests/tagged_ops.rs
agg-ast/schema_derivation/src/schema_derivation_tests/untagged_ops.rs

This also includes an implementation of include-only $project derivation for testing purposes.

SQL-2365: Add schema derivation for Lookup, GraphLookup, and UnionWith

---

mongosql/src/air/desugarer/remove_id.rs
mongosql/src/air/desugarer/test.rs
mongosql/src/air/desugarer/testdata/desugar_all.yml
test-utils/src/query/mod.rs
tests/e2e_tests/ext_json_implicit_type_conversion.yml
tests/spec_tests/query_tests/group_by.yml
tests/spec_tests/query_tests/order_by.yml
tests/spec_tests/query_tests/where.yml

Change to the document comparison logic to also check that they keys match. 
It required some minor changes to our existing tests, many of which are expected with the fix.  One is unexpected related to count(distinct *) which I've mentioned to @mattChiaravalloti

SQL-2664: Fix document comparison logic in test runner to check for matching key

---

evergreen/mongosqltranslate.yml

This PR implements papertrail tracing for `libmongosqltranslate`.
Successful patch with product name `libmongosqltranslate-snapshot`: https://spruce.mongodb.com/version/67be1a44ec8b1d00078e5358/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

SQL-2608: Implement Papertrail flow for libmongosqltranslate

---

errors.md
mongosql/src/algebrizer/definitions.rs
mongosql/src/algebrizer/errors.rs
mongosql/src/algebrizer/test.rs
mongosql/src/mir/definitions.rs
mongosql/src/mir/schema/mod.rs
mongosql/src/mir/schema/test/stages/set.rs
tests/errors/algebrizer.yml
tests/spec_tests/query_tests/distinct.yml
tests/spec_tests/query_tests/union.yml

Implementing UNION distinct.  It differs a bit from the initial design, I applied some of the things we did for SELECT DISTINCT such as using the `__groupKey{}` alias.  
Added tests to confirm behavior, removed `skip_reasons` from the existing union distinct tests and moved them into `distinct.yml`

SQL-2620: Add support for UNION distinct

---

mongosql-cli/src/main.rs
mongosql/src/algebrizer/definitions.rs
tests/spec_tests/query_tests/distinct.yml

This resolves an issue where schema checking was failing when order by missing columns option is true and the query has `SELECT DISTINCT` and `ORDER BY`. 
It follows the behavior of Postgres that order by expressions must appear in the select list. 
Added a query test to confirm the behavior. 
Also added a fix in the mongosql-cli, for it to set the expected default of `allow_order_by_missing_columns = true`.

SQL-2688: Disallow order by missing cols for SELECT DISTINCT

---

semantics.md
tests/spec_tests/query_tests/order_by.yml

This PR updates the `ORDER BY` tests to never rely on implicit ordering. Additionally, I removed the `missing sorts before null` test and updated the spec because MongoDB doesn't work this way anymore.

SQL-2667: Ensure ordered tests order on all items in the select list

---

Cargo.lock
evergreen.yml
evergreen/mongosqltranslate.yml

This PR creates the augmented SBOM and fixes the `ring` vulnerability via `cargo update`. 
Successful patch: https://spruce.mongodb.com/version/67d9d1705124ef0007d9db93/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

SQL-2596: Implement the SBOM flow for libmongosqltranslate

---

agg-ast/schema_derivation/src/lib.rs
agg-ast/schema_derivation/src/match_schema_derivation.rs
agg-ast/schema_derivation/src/negative_normalize.rs
agg-ast/schema_derivation/src/schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation_tests/match_stage.rs
agg-ast/schema_derivation/src/schema_derivation_tests/stage.rs
mongosql/src/schema/definitions.rs
mongosql/src/schema/test.rs

Noticed our Document schema intersection was actually wrong in that requiring a key is smaller than not.

SQL-2537: Remove todos

---

mongosql-cli/src/main.rs

This PR updates the `mongosql-cli` to tolerate missing schema information. This allows more (valid) queries to be issued to `mongosql-cli`. Also, since we run in `Relaxed` schema checking mode by default, this enables a lot of flexibility with this tool, which I personally find to be a plus.
Examples (previously, these all errored with `Error: CliError("There is no schema information in database `test`, so all the collections will be assigned empty schemas. Therefore, SQL capabilities will be very limited. Hint: Please make sure to generate schemas before using the driver")`)
```
$ cargo run --bin mongosql-cli "select * from [{'a': 1}] arr"     
target_db: test,
target_collection: None,
result set schema:
{
"bsonType": "object",
"properties": {
"arr": {
"bsonType": "object",
"properties": …
```

SQL-2713: Update mongosql-cli to allow missing schema info

---

agg-ast/schema_derivation/src/lib.rs
agg-ast/schema_derivation/src/match_schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation_tests/expression.rs
agg-ast/schema_derivation/src/schema_derivation_tests/match_expr.rs

the update to $match: $reduce was (sort of) a driveby addressing the same core error message we were getting back from deserializing pipelines. This is the one array op we'll _need_ to handle this for -- for $filter, for example, we just investigate the input, but dont bother scanning the array, so $$this won't come up there!

SQL-2725: handle missing variable refs appropriately

---

mongosql/src/lib.rs
mongosql/src/test.rs

Added SetQuantifier::Distinct to the pattern matching for getting select order. 
This is a fix for the issue where results were not being shown when running a DISTINCT query through DBeaver.

SQL-2732: Allow Distinct queries to return select order

---

evergreen.yml

The perf.send command is no longer being maintained and is in a maintenance state and will be decommissioned eventually. It has been replaced instead by a new end point that users are able to call from their evergreen files; [this doc](https://github.com/10gen/performance-tooling-docs/blob/main/getting_started/migrating_from_perfSend_to_sps.md) outlines a drop in solution that we apply to the existing evergreen config file in this PR.
This PR updates the Mongosql project to send performance data downstream using the newest supported method.
Successful patch:
https://spruce.mongodb.com/version/6815002246fcad0007eeeca9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

DEVPROD-17414 - Replace perf.send with direct API call

---

agg-ast/ast/src/custom_serde.rs
agg-ast/ast/src/definitions.rs
agg-ast/ast/src/serde_test.rs
agg-ast/schema_derivation/src/match_schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation_tests/tagged_ops.rs
mongosql/src/mir/definitions.rs
mongosql/src/mir/optimizer/use_def_analysis/mod.rs
service/src/service/translate_sql_service.rs
test-utils/src/build_utils/templates/schema_derivation_test_body_template
test-utils/src/index/mod.rs
test-utils/src/lib.rs
test-utils/src/query/mod.rs
test-utils/src/schema_derivation/mod.rs
tests/schema_derivation_tests/query_spec_tests/array.yml
tests/schema_derivation_tests/query_spec_tests/from_array.yml
tests/schema_derivation_tests/query_spec_tests/identifier.yml
tests/schema_derivation_tests/query_spec_tests/literal.yml
tests/schema_derivation_tests/query_spec_tests/operators_arithmetic.yml
tests/schema_derivation_tests/query_spec_tests/operators_precedence.yml

At implementation time, it became clear that there weren't as many operators / stages effected as previously thought, and as such, the easiest way to implement this was to handle during deserialization rather than during derivation / translation. 
If, eg, we expect a string argument, we can get that string by deserializing the expression, and getting the value from either a. the literal value or b. the untagged $literal operator, where the first (and only) argument will be a literal value.

SQL-2752: improve $literal ergonomics

---

agg-ast/schema_derivation/src/schema_derivation.rs
agg-ast/schema_derivation/src/schema_derivation_tests/stage.rs

Additional details in the ticket regarding the specific case this covers. Open to any ideas that might improve precision, but this does ensure correctness.
Unioning the documents is not ideal, but something like {$addFields: {a: {b: {c: ...}}}} could be arbitrarily nested and a full traversal to determine overwriting vs inserting rules would involve a potentially complex algorithm. This is correct but imprecise. This pattern also strikes me as potentially unlikely (I would imagine anything achieving this from a users end would more likely be achieved by a $project assignment).
Below is an example of the translated tpch-1 pipeline. I am curious why we have _both_ the addFields followed by the project assignment, which seemingly do the same thing, and maybe this is also a place we can …

SQL-2851: handle $addFields for document fields
